# Copyright 2025 Tetrate
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
    service: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      version: v1
  template:
    metadata:
      labels:
        app: redis
        version: v1
    spec:
      serviceAccountName: redis
      containers:
        - name: redis
          image: redis:7.2.4
          args:
            - /etc/redis/redis.conf
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 1
            periodSeconds: 5
            tcpSocket:
              port: 6379
          volumeMounts:
            - name: config
              mountPath: /etc/redis
              readOnly: true
            - name: certs
              mountPath: /etc/redis/certs
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: redis-config
        - name: certs
          secret:
            secretName: redis-certs
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  namespace: redis
data:
  redis.conf: |
    # Only accept TLS connections
    port 0
    tls-port 6379
    
    # Configure user credentials
    user default off
    user authservice on +@all ~* >redis-pass
    
    # Configure server certificates and require mTLS from clients
    tls-cert-file /etc/redis/certs/tls.crt
    tls-key-file /etc/redis/certs/tls.key
    tls-ca-cert-file /etc/redis/certs/ca.crt
