cc_test(
    name = "serviceimpl_test",
    srcs = ["serviceimpl_test.cc"],
    data = ["//test/fixtures"],
    deps = [
        "//src/config",
        "//src/service:serviceimpl",
        "@com_github_grpc_grpc//:grpc++",
        "@com_google_googletest//:gtest_main",
    ],
)
