load("//bazel:bazel.bzl", "xx_library")

package(default_visibility = ["//visibility:public"])

xx_library(
    name = "shared_test_helpers",
    srcs = [],
    hdrs = [
        "assertions.h",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
