load("//bazel:bazel.bzl", "authsvc_cc_library")

package(default_visibility = ["//visibility:public"])

authsvc_cc_library(
    name = "shared_test_helpers",
    srcs = [],
    hdrs = [
        "assertions.h",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
