#
# A simple example of enabling authentication for some services.
# See docs: https://istio.io/docs/tasks/security/authentication/authn-policy/#end-user-authentication
#

---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "bookinfo-authn-policy"
  namespace: default
spec:
  targets:
    # Enable authentication for the following services.
    # Note: `request.auth` only appears on the ServiceRoleBinding's or AuthorizationPolicy's for the following services
    - name: productpage
    - name: reviews
  origins:
    - jwt:
        issuer: https://demo.example.replace.me.com/oauth/token
        jwksUri: https://demo.example.replace.me.com/token_keys
  principalBinding: USE_ORIGIN
