cc_proto_library(
    name = "config_cc",
    visibility = ["//visibility:public"],
    deps = ["//config/common:config_proto"],
)

proto_library(
    name = "config_proto",
    srcs = ["config.proto"],
    visibility = ["//visibility:public"],
)
