name: Master Commit

on:
  push:
    branches: 
      - master

jobs:
  build:
    using: 'docker'
    image: 'Dockerfile'
    steps:
    - uses: actions/checkout@v1
    - name: make test
      run: make test
