name: PR Testing

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Bazel
      run: sudo build/install-bazel.sh
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install make cmake ninja-build build-essential
    - name: make test
      run: make test
