name: PR Testing

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/cf-identity-service-oak/authservice-build-env:2019-10-23
    steps:
    - uses: actions/checkout@v1
    - name: make clean
      run: make clean
    - name: make test
      run: make test
